-- payp test database seed - Oracle 23 Free
-- Creates the same sample schema as seed.sql, adapted for Oracle dialect.
-- Uses IDENTITY columns (Oracle 12c+) for auto-increment.
--
-- gvenzl/oracle-free runs init scripts as SYS in the CDB root; we switch
-- into the app PDB and run as the APP_USER schema (payp).

ALTER SESSION SET CONTAINER = PAYP_TEST;
ALTER SESSION SET CURRENT_SCHEMA = PAYP;

CREATE TABLE customers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    region VARCHAR2(50) NOT NULL,
    segment VARCHAR2(20) DEFAULT 'free' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE customers IS 'Customer accounts';
COMMENT ON COLUMN customers.segment IS 'free, starter, pro, enterprise';
COMMENT ON COLUMN customers.region IS 'EU-West, EU-East, NA, APAC';

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(12, 2) NOT NULL,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);
COMMENT ON TABLE products IS 'Product catalog';

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    status NUMBER(5) DEFAULT 1 NOT NULL,
    total_amount NUMBER(12, 2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);
COMMENT ON TABLE orders IS 'Customer orders';
COMMENT ON COLUMN orders.status IS '1=pending, 2=confirmed, 3=shipped, 4=delivered, 5=cancelled';

CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);

CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER(10) DEFAULT 1 NOT NULL,
    unit_price NUMBER(12, 2) NOT NULL,
    total NUMBER(12, 2) NOT NULL,
    CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);

CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    amount NUMBER(12, 2) NOT NULL,
    payment_method VARCHAR2(50) NOT NULL,
    status VARCHAR2(20) DEFAULT 'pending' NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
COMMENT ON TABLE payments IS 'Payment transactions';
COMMENT ON COLUMN payments.payment_method IS 'credit_card, bank_transfer, paypal';
COMMENT ON COLUMN payments.status IS 'pending, completed, failed, refunded';

CREATE INDEX idx_payments_order_id ON payments(order_id);

-- Sample data

INSERT INTO customers (name, email, region, segment) VALUES ('Alice Johnson', 'alice@example.com', 'NA', 'pro');
INSERT INTO customers (name, email, region, segment) VALUES ('Bob Smith', 'bob@example.com', 'EU-West', 'enterprise');
INSERT INTO customers (name, email, region, segment) VALUES ('Charlie Chen', 'charlie@example.com', 'APAC', 'starter');
INSERT INTO customers (name, email, region, segment) VALUES ('Diana Mueller', 'diana@example.com', 'EU-East', 'pro');
INSERT INTO customers (name, email, region, segment) VALUES ('Eve Williams', 'eve@example.com', 'NA', 'free');
INSERT INTO customers (name, email, region, segment) VALUES ('Frank Tanaka', 'frank@example.com', 'APAC', 'enterprise');
INSERT INTO customers (name, email, region, segment) VALUES ('Grace Kim', 'grace@example.com', 'EU-West', 'starter');
INSERT INTO customers (name, email, region, segment) VALUES ('Henry Larsson', 'henry@example.com', 'EU-West', 'pro');
INSERT INTO customers (name, email, region, segment) VALUES ('Ivy Patel', 'ivy@example.com', 'APAC', 'free');
INSERT INTO customers (name, email, region, segment) VALUES ('Jack Novak', 'jack@example.com', 'EU-East', 'starter');

INSERT INTO products (name, category, price) VALUES ('Basic Plan', 'subscription', 9.99);
INSERT INTO products (name, category, price) VALUES ('Pro Plan', 'subscription', 29.99);
INSERT INTO products (name, category, price) VALUES ('Enterprise Plan', 'subscription', 99.99);
INSERT INTO products (name, category, price) VALUES ('API Credits 1K', 'credits', 5.00);
INSERT INTO products (name, category, price) VALUES ('API Credits 10K', 'credits', 40.00);
INSERT INTO products (name, category, price) VALUES ('Storage 100GB', 'addon', 15.00);
INSERT INTO products (name, category, price) VALUES ('Priority Support', 'addon', 49.99);
INSERT INTO products (name, category, price) VALUES ('Custom Integration', 'service', 299.99);

INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (1, 4, 29.99, TIMESTAMP '2025-01-15 10:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (2, 4, 149.98, TIMESTAMP '2025-01-20 14:30:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (1, 4, 5.00, TIMESTAMP '2025-02-01 09:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (3, 4, 9.99, TIMESTAMP '2025-02-10 11:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (4, 3, 44.99, TIMESTAMP '2025-03-01 16:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (2, 4, 99.99, TIMESTAMP '2025-03-15 08:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (5, 5, 9.99, TIMESTAMP '2025-03-20 12:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (6, 2, 399.98, TIMESTAMP '2025-04-01 10:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (1, 1, 29.99, TIMESTAMP '2025-04-02 09:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (7, 4, 29.99, TIMESTAMP '2025-02-15 13:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (8, 4, 79.98, TIMESTAMP '2025-03-05 15:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (3, 3, 45.00, TIMESTAMP '2025-03-25 11:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (9, 1, 9.99, TIMESTAMP '2025-04-01 08:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (10, 4, 29.99, TIMESTAMP '2025-01-25 10:00:00 UTC');
INSERT INTO orders (customer_id, status, total_amount, created_at) VALUES (4, 4, 99.99, TIMESTAMP '2025-02-20 14:00:00 UTC');

INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (1, 2, 1, 29.99, 29.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (2, 3, 1, 99.99, 99.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (2, 7, 1, 49.99, 49.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (3, 4, 1, 5.00, 5.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (4, 1, 1, 9.99, 9.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (5, 2, 1, 29.99, 29.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (5, 6, 1, 15.00, 15.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (6, 3, 1, 99.99, 99.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (7, 1, 1, 9.99, 9.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (8, 8, 1, 299.99, 299.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (8, 3, 1, 99.99, 99.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (9, 2, 1, 29.99, 29.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (10, 2, 1, 29.99, 29.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (11, 2, 1, 29.99, 29.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (11, 7, 1, 49.99, 49.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (12, 5, 1, 40.00, 40.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (12, 4, 1, 5.00, 5.00);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (13, 1, 1, 9.99, 9.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (14, 2, 1, 29.99, 29.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price, total) VALUES (15, 3, 1, 99.99, 99.99);

INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (1, 29.99, 'credit_card', 'completed', TIMESTAMP '2025-01-15 10:05:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (2, 149.98, 'bank_transfer', 'completed', TIMESTAMP '2025-01-21 09:00:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (3, 5.00, 'credit_card', 'completed', TIMESTAMP '2025-02-01 09:01:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (4, 9.99, 'paypal', 'completed', TIMESTAMP '2025-02-10 11:05:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (5, 44.99, 'credit_card', 'completed', TIMESTAMP '2025-03-01 16:10:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (6, 99.99, 'bank_transfer', 'completed', TIMESTAMP '2025-03-15 10:00:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (7, 9.99, 'paypal', 'failed', NULL);
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (8, 399.98, 'bank_transfer', 'pending', NULL);
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (10, 29.99, 'credit_card', 'completed', TIMESTAMP '2025-02-15 13:05:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (11, 79.98, 'credit_card', 'completed', TIMESTAMP '2025-03-05 15:10:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (12, 45.00, 'paypal', 'completed', TIMESTAMP '2025-03-25 11:05:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (14, 29.99, 'credit_card', 'completed', TIMESTAMP '2025-01-25 10:05:00 UTC');
INSERT INTO payments (order_id, amount, payment_method, status, paid_at) VALUES (15, 99.99, 'bank_transfer', 'completed', TIMESTAMP '2025-02-20 14:30:00 UTC');

COMMIT;
