"""Reviewer (Model B) — validates SQL generated by executor (Model A).

Three possible verdicts:
- APPROVE: execute as-is
- SAFER_ALTERNATIVE: suggest improved SQL, Model A decides to use or keep original
- HARD_BLOCK: user must explicitly override (DROP DB, DROP SCHEMA, etc.)
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum

from payp.core.llm import LLMClient


class Verdict(str, Enum):
    APPROVE = "approve"
    SAFER = "safer"
    HARD_BLOCK = "hard_block"


@dataclass
class Review:
    verdict: Verdict
    reason: str  # 1-2 sentence explanation
    safer_sql: str | None = None  # Alternative SQL if verdict is SAFER
    raw_response: str = ""  # For debugging


REVIEW_PROMPT = """You are a database safety reviewer. Analyze this SQL for risks.

User's original request: {user_request}
Generated SQL: {sql}
Database: PostgreSQL
Connection: {connection}
Statement type: {stmt_type}
{schema_context}

Respond in EXACTLY this format (no markdown, no code fences):
VERDICT: [APPROVE | SAFER | HARD_BLOCK]
REASON: [1-2 sentences]
SAFER_SQL: [only if VERDICT is SAFER; otherwise write "N/A"]

CRITICAL RULES for SAFER_SQL:
- MUST be complete, executable SQL. No placeholders, no angle brackets, no square brackets.
- DO NOT write "WHERE condition" or "WHERE <condition>" or "WHERE [criteria]".
- If you cannot write a concrete safer version (e.g., user wants to delete all rows and that IS their intent), respond with APPROVE instead of SAFER.
- Wrapping in BEGIN/COMMIT is fine but alone is NOT a safer version — needs something else (LIMIT, specific WHERE).
- Examples of valid SAFER_SQL:
  * DELETE FROM orders WHERE created_at < '2020-01-01';  (adds time filter)
  * UPDATE products SET price = price * 1.1 WHERE category = 'books';  (scopes by known column)
  * DELETE FROM orders WHERE status = 5 LIMIT 100;  (batches the operation — but note PostgreSQL doesn't support LIMIT on DELETE, use CTE instead)

Verdict rules:
- APPROVE: SQL is reasonable OR user explicitly wants the operation as stated.
- SAFER: You can write CONCRETE executable safer SQL achieving the SAME goal.
- HARD_BLOCK: Only for DROP DATABASE, DROP SCHEMA, or TRUNCATE.

Be pragmatic. If user says "delete all customers" and means it, APPROVE. Only use SAFER when you have concrete executable SQL."""


class Reviewer:
    """Model B — reviews SQL generated by Model A."""

    def __init__(self, llm: LLMClient) -> None:
        self.llm = llm

    async def review(
        self,
        sql: str,
        user_request: str,
        stmt_type: str = "",
        connection: str = "unknown",
        schema_context: str = "",
    ) -> Review:
        """Send SQL to reviewer model, parse verdict."""
        reviewer_model = self.llm.get_reviewer_model()
        if not reviewer_model:
            # No reviewer configured — auto-approve with a note
            return Review(
                verdict=Verdict.APPROVE,
                reason="No reviewer model configured",
                raw_response="",
            )

        prompt_schema = f"\nSchema context:\n{schema_context}" if schema_context else ""
        prompt = REVIEW_PROMPT.format(
            user_request=user_request,
            sql=sql,
            connection=connection,
            stmt_type=stmt_type,
            schema_context=prompt_schema,
        )

        messages = [
            {"role": "system", "content": "You are a precise, terse database safety reviewer."},
            {"role": "user", "content": prompt},
        ]

        try:
            response = await self.llm.chat(messages, model=reviewer_model, stream=False)
            return _parse_review(response.content or "")
        except Exception as e:
            # If reviewer fails, default to requiring user approval
            return Review(
                verdict=Verdict.SAFER,
                reason=f"Reviewer failed ({e}). Proceed with caution.",
                raw_response=str(e),
            )


def _parse_review(raw: str) -> Review:
    """Parse reviewer response into a Review object."""
    verdict_match = re.search(r"VERDICT:\s*(APPROVE|SAFER|HARD_BLOCK)", raw, re.IGNORECASE)
    reason_match = re.search(r"REASON:\s*(.+?)(?=SAFER_SQL:|$)", raw, re.IGNORECASE | re.DOTALL)
    safer_match = re.search(r"SAFER_SQL:\s*(.+?)$", raw, re.IGNORECASE | re.DOTALL)

    if not verdict_match:
        # Unparseable — treat as safer/warning
        return Review(
            verdict=Verdict.SAFER,
            reason="Reviewer response unparseable — proceeding with caution",
            raw_response=raw,
        )

    verdict_str = verdict_match.group(1).upper()
    verdict = {
        "APPROVE": Verdict.APPROVE,
        "SAFER": Verdict.SAFER,
        "HARD_BLOCK": Verdict.HARD_BLOCK,
    }[verdict_str]

    reason = reason_match.group(1).strip() if reason_match else "No reason provided"

    safer_sql = None
    if verdict == Verdict.SAFER and safer_match:
        safer_raw = safer_match.group(1).strip()
        if safer_raw and safer_raw.upper() != "N/A":
            # Strip code fences if present
            candidate = re.sub(r"^```\w*\n?|```$", "", safer_raw, flags=re.MULTILINE).strip()
            # Validate — reject templates with placeholders
            if _is_valid_safer_sql(candidate):
                safer_sql = candidate
            else:
                # Reviewer gave a template, not executable SQL — downgrade to APPROVE
                # (original SQL will be shown to user for manual decision)
                verdict = Verdict.APPROVE
                reason = (
                    f"{reason} (Note: reviewer suggested improvement but provided "
                    f"a template, not executable SQL. Using original.)"
                )

    return Review(
        verdict=verdict,
        reason=reason,
        safer_sql=safer_sql,
        raw_response=raw,
    )


# Patterns that indicate template/placeholder SQL (not executable)
_PLACEHOLDER_PATTERNS = [
    r"<\w+>",                       # <condition>, <table>, etc.
    r"\[[^\]]+\]",                  # [condition], [criteria]
    r"\bWHERE\s+condition\b",       # WHERE condition
    r"\bWHERE\s+criteria\b",        # WHERE criteria
    r"\bWHERE\s+your_\w+",          # WHERE your_xxx
    r"\{[^}]+\}",                   # {placeholder}
    r"\bLIMIT\s*[;$]",              # LIMIT ; (empty limit)
    r"\bWHERE\s*[;$]",              # WHERE ; (empty where)
    r"--\s*Add\s+",                 # "-- Add specific condition"
    r"--\s*Specify\s+",             # "-- Specify ..."
    r"--\s*Replace\s+",             # "-- Replace this with..."
]


def _is_valid_safer_sql(sql: str) -> bool:
    """Check that safer SQL is executable, not a template."""
    if not sql or len(sql.strip()) < 10:
        return False
    for pattern in _PLACEHOLDER_PATTERNS:
        if re.search(pattern, sql, re.IGNORECASE):
            return False
    return True
